source:      .
destination: ./_site
baseurl:     /sparkling
gems: [jekyll-sitemap]
plugins:     ./_plugins
exclude: [Gemfile,Gemfile.lock,LICENSE,README.md,Tutorial.md,bin,data,dev-resources,doc,pom.xml,pom.xml.asc,project.clj,sparkling.iml,src,target,test,tmp]
permalink: /:title
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
